curl https://raw.githubusercontent.com/tensorflow/tensorflow/master/tensorflow/lite/examples/label_image/testdata/grace_hopper.bmp > /home/ubuntu/Desktop/sample/grace_hopper.bmp

curl https://storage.googleapis.com/download.tensorflow.org/models/mobilenet_v1_2018_02_22/mobilenet_v1_1.0_224.tgz | tar xzv -C /home/ubuntu/Desktop/sample/

curl https://storage.googleapis.com/download.tensorflow.org/models/mobilenet_v1_1.0_224_frozen.tgz | tar xzv -C /home/ubuntu/Desktop/sample/ mobilenet_v1_1.0_224/labels.txt

mv /home/ubuntu/Desktop/sample/mobilenet_v1_1.0_224/labels.txt /home/ubuntu/Desktop/sample/

python3 label_image.py \
  --model_file /home/ubuntu/Desktop/sample/mobilenet_v1_1.0_224.tflite \
  --label_file /home/ubuntu/Desktop/sample/labels.txt \
  --image /home/ubuntu/Desktop/sample/grace_hopper.bmp

import tensorflow as tf
print("TensorFlow version:", tf.__version__)

# Check TensorFlow Lite availability
try:
    interpreter = tf.lite.Interpreter(model_path="path_to_your_model.tflite")
    print("TensorFlow Lite is installed correctly!")
except Exception as e:
    print(f"TensorFlow Lite encountered an issue: {e}")

ubuntu@mtk-genio:~/Desktop/test$ python3 label_image.py \
  --model_file /home/ubuntu/Desktop/sample/mobilenet_v1_1.0_224.tflite \
  --label_file /home/ubuntu/Desktop/sample/labels.txt \
  --image /home/ubuntu/Desktop/sample/grace_hopper.bmp
Traceback (most recent call last):
  File "/home/ubuntu/Desktop/test/label_image.py", line 88, in <module>
    interpreter = tf.lite.Interpreter(
NameError: name 'tf' is not defined





ERRORE CON GPU

ubuntu@mtk-genio:~/Desktop/test/Sample$ python3 label_image.py --label_file labels_mobilenet_quant_v1_224.txt --image grace_hopper.jpg --model_file mobilenet_v1_1.0_224_quant.tflite -e /usr/lib/libarmnnDelegate.so.29 -o "backends:GpuAcc,CpuAcc"
Loading external delegate from /usr/lib/libarmnnDelegate.so.29 with args: {'backends': 'GpuAcc,CpuAcc'}
Traceback (most recent call last):
  File "/home/ubuntu/Desktop/test/Sample/label_image.py", line 85, in <module>
    tflite.load_delegate(args.ext_delegate, ext_delegate_options)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tflite_runtime/interpreter.py", line 166, in load_delegate
    delegate = Delegate(library, options)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tflite_runtime/interpreter.py", line 73, in __init__
    self._library = ctypes.pydll.LoadLibrary(library)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/libarmnnDelegate.so.29: cannot open shared object file: No such file or directory
Exception ignored in: <function Delegate.__del__ at 0xffff8922f400>
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tflite_runtime/interpreter.py", line 109, in __del__
    if self._library is not None:
AttributeError: 'Delegate' object has no attribute '_library'
